workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: latest
      java: 17
    trigger:
      branch:
        - main
    scripts:
      - name: Set up Flutter
        script: | 
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - raushankushawaha7@gmail.com # Replace with your email to receive build notifications
        success:
          enabled: true
        failure:
          enabled: true
